export const ADD_ARTICLE = "ADD_ARTICLE";

export const UPDATE_TAB = "UPDATE_TAB";

export const UPDATE_SUMMONING = "UPDATE_SUMMONING";

export const UPDATE_DESUMMONING = "UPDATE_DESUMMONING";

export const UPDATE_POSSE = "UPDATE_POSSE";

export const UPDATE_INDEPENDENCE = "UPDATE_INDEPENDENCE";
